-- DROP and CREATE DATABASE
DROP DATABASE IF EXISTS Hospital;
CREATE DATABASE Hospital;
USE Hospital;

-- =========================================
-- Sequence Tables
-- =========================================
CREATE TABLE DR_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT PRIMARY KEY
) AUTO_INCREMENT = 1;

CREATE TABLE PATIENT_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT PRIMARY KEY
) AUTO_INCREMENT = 1;

CREATE TABLE NURSE_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT PRIMARY KEY
) AUTO_INCREMENT = 1;

CREATE TABLE REG_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT PRIMARY KEY
) AUTO_INCREMENT = 1;

-- =========================================
-- DOCTOR Table
-- =========================================
CREATE TABLE DOCTOR (
    DR_ID CHAR(7) NOT NULL PRIMARY KEY,
    DR_LNAME VARCHAR(20) NOT NULL,
    DR_FNAME VARCHAR(20) NOT NULL,
    DR_CNUM CHAR(11) NOT NULL,
    DR_SPECIALIZATION CHAR(18) NOT NULL,
    DR_NUM_STATION CHAR(6) NOT NULL
);

DELIMITER $$
CREATE TRIGGER before_dr_insert
BEFORE INSERT ON DOCTOR
FOR EACH ROW
BEGIN
    DECLARE next_id INT;
    INSERT INTO DR_SEQUENCE () VALUES ();
    SET next_id = LAST_INSERT_ID();
    SET NEW.DR_ID = CONCAT('D', LPAD(next_id, 6, '0'));
END$$
DELIMITER ;

-- =========================================
-- H_ROOM Table
-- =========================================
CREATE TABLE H_ROOM (
    ROOM_NUM INT NOT NULL PRIMARY KEY,
    ROOM_TYPE CHAR(13) NOT NULL,
    ROOM_AVAILABILITY CHAR(13) NOT NULL
);

-- =========================================
-- PATIENT Table
-- =========================================
CREATE TABLE PATIENT (
    PATIENT_ID CHAR(7) NOT NULL PRIMARY KEY, -- Format: P000001
    PATIENT_TYPE CHAR(10) NOT NULL,
    PATIENT_LNAME VARCHAR(20) NOT NULL,
    PATIENT_FNAME VARCHAR(40) NOT NULL,
    PATIENT_MED_HISTORY TEXT NOT NULL,
    PATIENT_ADMI_TIME TIME NOT NULL,
    PATIENT_ADMI_DATE DATE NOT NULL
);

DELIMITER $$
CREATE TRIGGER before_patient_insert
BEFORE INSERT ON PATIENT
FOR EACH ROW
BEGIN
    DECLARE next_id INT;
    INSERT INTO PATIENT_SEQUENCE () VALUES ();
    SET next_id = LAST_INSERT_ID();
    SET NEW.PATIENT_ID = CONCAT('P', LPAD(next_id, 6, '0'));
END$$
DELIMITER ;

-- =========================================
-- NURSE Table
-- =========================================
CREATE TABLE NURSE (
    NURSE_ID CHAR(7) NOT NULL PRIMARY KEY,
    NURSE_LNAME VARCHAR(20) NOT NULL,
    NURSE_FNAME VARCHAR(40) NOT NULL,
    NURSE_NUM_STATION CHAR(6) NOT NULL,
    NURSE_SPECIALIZATION CHAR(10) NOT NULL,
    PATIENT_ID CHAR(7),
    DR_ID CHAR(7),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID) ON DELETE SET NULL,
    FOREIGN KEY (DR_ID) REFERENCES DOCTOR(DR_ID) ON DELETE SET NULL
);

DELIMITER $$
CREATE TRIGGER before_nurse_insert
BEFORE INSERT ON NURSE
FOR EACH ROW
BEGIN
    DECLARE next_id INT;
    INSERT INTO NURSE_SEQUENCE () VALUES ();
    SET next_id = LAST_INSERT_ID();
    SET NEW.NURSE_ID = CONCAT('N', LPAD(next_id, 6, '0'));
END$$
DELIMITER ;

-- =========================================
-- REGISTRAR Table
-- =========================================
CREATE TABLE REGISTRAR (
    REG_ID CHAR(7) NOT NULL PRIMARY KEY,
    REG_LNAME VARCHAR(20) NOT NULL,
    REG_FNAME VARCHAR(40) NOT NULL,
    REG_NUM_STATION CHAR(40) NOT NULL,
    REG_MOP VARCHAR(20) NOT NULL,
    REG_SHIFT CHAR(9) NOT NULL,
    PATIENT_ID CHAR(7),
    ROOM_NUM INT,
    NURSE_ID CHAR(7),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID) ON DELETE SET NULL,
    FOREIGN KEY (ROOM_NUM) REFERENCES H_ROOM(ROOM_NUM) ON DELETE SET NULL,
    FOREIGN KEY (NURSE_ID) REFERENCES NURSE(NURSE_ID) ON DELETE SET NULL
);

DELIMITER $$
CREATE TRIGGER before_reg_insert
BEFORE INSERT ON REGISTRAR
FOR EACH ROW
BEGIN
    DECLARE next_id INT;
    INSERT INTO REG_SEQUENCE () VALUES ();
    SET next_id = LAST_INSERT_ID();
    SET NEW.REG_ID = CONCAT('R', LPAD(next_id, 6, '0'));
END$$
DELIMITER ;

-- =========================================
-- Verify Tables
-- =========================================
SHOW TABLES;
DESCRIBE DOCTOR;
DESCRIBE PATIENT;
DESCRIBE NURSE;
DESCRIBE REGISTRAR;
DESCRIBE H_ROOM;

SELECT * FROM PATIENT;
SELECT * FROM DOCTOR;
SELECT * FROM H_ROOM;
SELECT * FROM REGISTRAR;

ALTER TABLE REGISTRAR
DROP COLUMN PASSWORD;
